USE [XYZ]
GO
ALTER TABLE [dbo].[USER_ERROR] DROP CONSTRAINT [FK_USER_ERROR_USER]
GO
ALTER TABLE [dbo].[RECEIPT] DROP CONSTRAINT [FK_RECEIPT_USER]
GO
ALTER TABLE [dbo].[ORDER] DROP CONSTRAINT [FK_ORDER_USER]
GO
ALTER TABLE [dbo].[ORDER] DROP CONSTRAINT [FK_ORDER_PAYSERA]
GO
ALTER TABLE [dbo].[ORDER] DROP CONSTRAINT [FK_ORDER_PAYPAL]
GO
/****** Object:  Index [IDX_USER_ERROR_USER_ID]    Script Date: 3/10/2025 11:25:26 PM ******/
DROP INDEX [IDX_USER_ERROR_USER_ID] ON [dbo].[USER_ERROR]
GO
/****** Object:  Index [IDX_RECEIPT_USER_ID]    Script Date: 3/10/2025 11:25:26 PM ******/
DROP INDEX [IDX_RECEIPT_USER_ID] ON [dbo].[RECEIPT]
GO
/****** Object:  Table [dbo].[USER_ERROR]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USER_ERROR]') AND type in (N'U'))
DROP TABLE [dbo].[USER_ERROR]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USER]') AND type in (N'U'))
DROP TABLE [dbo].[USER]
GO
/****** Object:  Table [dbo].[RECEIPT]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RECEIPT]') AND type in (N'U'))
DROP TABLE [dbo].[RECEIPT]
GO
/****** Object:  Table [dbo].[PAYSERA_GATEWAY_ORDER]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAYSERA_GATEWAY_ORDER]') AND type in (N'U'))
DROP TABLE [dbo].[PAYSERA_GATEWAY_ORDER]
GO
/****** Object:  Table [dbo].[PAYPAL_GATEWAY_ORDER]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAYPAL_GATEWAY_ORDER]') AND type in (N'U'))
DROP TABLE [dbo].[PAYPAL_GATEWAY_ORDER]
GO
/****** Object:  Table [dbo].[ORDER]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDER]') AND type in (N'U'))
DROP TABLE [dbo].[ORDER]
GO
/****** Object:  Table [dbo].[APP_ERROR]    Script Date: 3/10/2025 11:25:26 PM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[APP_ERROR]') AND type in (N'U'))
DROP TABLE [dbo].[APP_ERROR]
GO
USE [master]
GO
/****** Object:  Database [XYZ]    Script Date: 3/10/2025 11:25:26 PM ******/
DROP DATABASE [XYZ]
GO
/****** Object:  Database [XYZ]    Script Date: 3/10/2025 11:25:26 PM ******/
CREATE DATABASE [XYZ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'XYZ', FILENAME = N'C:\Users\User\XYZ.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'XYZ_log', FILENAME = N'C:\Users\User\XYZ_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [XYZ] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [XYZ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [XYZ] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [XYZ] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [XYZ] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [XYZ] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [XYZ] SET ARITHABORT OFF 
GO
ALTER DATABASE [XYZ] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [XYZ] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [XYZ] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [XYZ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [XYZ] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [XYZ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [XYZ] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [XYZ] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [XYZ] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [XYZ] SET  DISABLE_BROKER 
GO
ALTER DATABASE [XYZ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [XYZ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [XYZ] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [XYZ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [XYZ] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [XYZ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [XYZ] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [XYZ] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [XYZ] SET  MULTI_USER 
GO
ALTER DATABASE [XYZ] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [XYZ] SET DB_CHAINING OFF 
GO
ALTER DATABASE [XYZ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [XYZ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [XYZ] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [XYZ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [XYZ] SET QUERY_STORE = OFF
GO
USE [XYZ]
GO
/****** Object:  Table [dbo].[APP_ERROR]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[APP_ERROR](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
	[MESSAGE] [nvarchar](200) NOT NULL,
	[STACKTRACE] [nvarchar](max) NOT NULL,
	[ADDITIONAL_TEXT] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
	[ORDER_NUMBER] [bigint] NOT NULL,
	[PAYSERA_ORDER_ID] [bigint] NULL,
	[PAYPAL_ORDER_ID] [bigint] NULL,
	[PAYABLE_AMOUNT] [decimal](18, 2) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[ORDER_STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYPAL_GATEWAY_ORDER]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYPAL_GATEWAY_ORDER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PAYSERA_GATEWAY_ORDER]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYSERA_GATEWAY_ORDER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECEIPT]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEIPT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
	[RECEIPT_ID] [nvarchar](100) NOT NULL,
	[ORDER_NUMBER] [bigint] NOT NULL,
	[GATEWAY_TRANSACTION_ID] [nvarchar](max) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
 CONSTRAINT [PK_dbo.USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_ERROR]    Script Date: 3/10/2025 11:25:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_ERROR](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[DB_RECORD_CREATION_TIME] [datetime] NOT NULL,
	[DB_RECORD_UPDATE_TIME] [datetime] NULL,
	[MESSAGE] [nvarchar](200) NOT NULL,
	[STACKTRACE] [nvarchar](max) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[ADDITIONAL_TEXT] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IDX_RECEIPT_USER_ID]    Script Date: 3/10/2025 11:25:27 PM ******/
CREATE NONCLUSTERED INDEX [IDX_RECEIPT_USER_ID] ON [dbo].[RECEIPT]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_USER_ERROR_USER_ID]    Script Date: 3/10/2025 11:25:27 PM ******/
CREATE NONCLUSTERED INDEX [IDX_USER_ERROR_USER_ID] ON [dbo].[USER_ERROR]
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_PAYPAL] FOREIGN KEY([PAYPAL_ORDER_ID])
REFERENCES [dbo].[PAYPAL_GATEWAY_ORDER] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_PAYPAL]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_PAYSERA] FOREIGN KEY([PAYSERA_ORDER_ID])
REFERENCES [dbo].[PAYSERA_GATEWAY_ORDER] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_PAYSERA]
GO
ALTER TABLE [dbo].[ORDER]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[ORDER] CHECK CONSTRAINT [FK_ORDER_USER]
GO
ALTER TABLE [dbo].[RECEIPT]  WITH CHECK ADD  CONSTRAINT [FK_RECEIPT_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[RECEIPT] CHECK CONSTRAINT [FK_RECEIPT_USER]
GO
ALTER TABLE [dbo].[USER_ERROR]  WITH CHECK ADD  CONSTRAINT [FK_USER_ERROR_USER] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[USER] ([ID])
GO
ALTER TABLE [dbo].[USER_ERROR] CHECK CONSTRAINT [FK_USER_ERROR_USER]
GO
USE [master]
GO
ALTER DATABASE [XYZ] SET  READ_WRITE 
GO
