using XYZ.Models.Features.Billing.Data.Dto;

namespace XYZ.Logic.Common.Interfaces
{
    /// <summary>
    /// Main receipt logic class for receipt CRUD's.
    /// </summary>
    public interface IReceiptLogic
    {
        /// <summary>
        /// Gets receipt by receipt string identifier (not main).
        /// </summary>
        /// <param name="receiptId">Receipt string identifier that was generated by server.</param>
        /// <returns>Receipt result if found, null otherwise.</returns>
        /// <exception cref="ArgumentNullException"></exception>
        Task<ReceiptDto?> GetReceipt(string receiptId);

        /// <summary>
        /// Main receipt saving logic.
        /// </summary>
        /// <param name="receipt">Order receipt.</param>
        /// <returns>Saved receipt main identifier.</returns>
        /// <exception cref="ArgumentNullException">Thrown if parameter is null</exception>
        Task<long> SaveReceipt(ReceiptDto? receipt);
    }
}