using XYZ.DataAccess.Tables.Base;

namespace XYZ.DataAccess.Tables.RECEIPT_TABLE
{
    /// <summary>
    /// RECEIPT table representation in database, contains errors specific receipt which is bound to order, POCO
    /// </summary>
    public class RECEIPT : TABLE_BASE
    {
        /// <summary>
        /// FK to USER table, main user identifier.
        /// </summary>
        public long USER_ID { get; set; }

        /// <summary>
        /// Receipt string identier generated by server during receipt creation.
        /// </summary>
        public string RECEIPT_ID { get; set; }

        /// <summary>
        /// FK to ORDER_NUMBER in ORDER table.
        /// </summary>
        public long ORDER_NUMBER { get; set; }

        /// <summary>
        /// Specific gateway transaction id, this id comes from 3-rd party API.
        /// </summary>
        public string GATEWAY_TRANSACTION_ID { get; set; }
    }
}
